# Copy this file to .streamlit/secrets.toml and add your actual API keys

# Get your Gemini API key from: https://ai.google.dev/
GEMINI_API_KEY = "your_gemini_api_key_here"

# Get your Serper API key from: https://serper.dev/
SERPER_API_KEY = "your_serper_api_key_here"

# Get your Browserless API key from: https://www.browserless.io/
BROWSERLESS_API_KEY = "your_browserless_api_key_here"
